version: '3.7'
services:
    backend:
        container_name: backend
        build:
            context: backend
        environment:
          - FLASK_APP=server.py
        env_file:
          - .env
        depends_on:
          - mongodb
        volumes:
          - ./backend:/src
    frontend:
        container_name: frontend
        ports:
          - 80:80
        build:
            context: frontend
        depends_on:
          - backend
    
    mongodb:
        image: mongo:latest
        container_name: mongodb
        ports:
          - 27017:27017
        volumes:
          - mongodb_data:/data/db
        command: [--auth]
        restart: always
volumes:
    mongodb_data:
        

